#Database
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: admin
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: emaildb

#Server
SERVER_PORT: 9000
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: developer.reis@gmail.com
EMAIL_PASSWORD: qfwx zjgf dtoa muld
VERIFY_EMAIL_HOST: http://localhost:8080